### ISSUE TITLE
Zookeeper over MTLS Istio doen't work

### ISSUE THREAD

**Issue by 2phost** [pravega/zookeeper-operator#192]
Hello,

I am trying to run a cluster of 3 Zookeepers over Istio MTLS. I know that the Istio support was already merged, as such, I decided to give it a try.

The first node seems to be ok, but as soon as the others nodes start, everything goes wrong.
Please note that everything runs normally when I remove Istio from this namespace.

This is my cluster configuration:

> apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zk-with-istio
  namespace: zookeeper-system
spec:
  replicas: 3
  config:
    initLimit: 10
    tickTime: 200
    syncLimit: 5
    quorumListenOnAllIPs: true
  image:
    pullPolicy: Always
    repository: xxxxxxxx/library/zookeeper
    tag: v0.2.7-11
  persistence:
    reclaimPolicy: Delete
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi

I tried to increase the initLimit and syncTime, but the problem remains.

Some errors from the node 2 (the logs from node 3 are the same):

> 2020-06-04 14:46:29,289 [myid:2] - WARN  [RecvWorker:1:QuorumCnxManager$RecvWorker@1176] - Connection broken for id 1, my id = 2, error = 
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$RecvWorker.run(QuorumCnxManager.java:1161)
2020-06-04 14:46:29,289 [myid:2] - WARN  [RecvWorker:1:QuorumCnxManager$RecvWorker@1179] - Interrupting SendWorker
2020-06-04 14:46:29,290 [myid:2] - WARN  [SendWorker:1:QuorumCnxManager$SendWorker@1092] - Interrupted while waiting for message on queue
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.pollSendQueue(QuorumCnxManager.java:1243)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.access$700(QuorumCnxManager.java:78)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$SendWorker.run(QuorumCnxManager.java:1080)
2020-06-04 14:46:29,292 [myid:2] - WARN  [SendWorker:1:QuorumCnxManager$SendWorker@1102] - Send worker leaving thread  id 1 my id = 2
2020-06-04 14:46:31,712 [myid:2] - INFO  [NIOWorkerThread-1:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:59316
2020-06-04 14:46:36,734 [myid:2] - WARN  [NIOWorkerThread-2:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2020-06-04 14:46:40,584 [myid:2] - WARN  [NIOWorkerThread-1:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2020-06-04 14:46:41,715 [myid:2] - INFO  [NIOWorkerThread-2:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:59612
2020-06-04 14:46:42,406 [myid:2] - INFO  [NIOWorkerThread-1:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:59640
2020-06-04 14:46:42,822 [myid:2] - WARN  [NIOWorkerThread-2:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2020-06-04 14:46:46,675 [myid:2] - WARN  [NIOWorkerThread-1:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2020-06-04 14:46:48,736 [myid:2] - INFO  [NIOWorkerThread-2:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:59850
2020-06-04 14:46:49,187 [myid:2] - WARN  [NIOWorkerThread-1:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2020-06-04 14:46:51,707 [myid:2] - INFO  [NIOWorkerThread-2:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:59924
2020-06-04 14:46:54,882 [myid:2] - INFO  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):FastLeaderElection@919] - Notification time out: 51200
2020-06-04 14:46:54,894 [myid:2] - WARN  [RecvWorker:1:QuorumCnxManager$RecvWorker@1176] - Connection broken for id 1, my id = 2, error = 
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$RecvWorker.run(QuorumCnxManager.java:1161)
2020-06-04 14:46:54,894 [myid:2] - WARN  [RecvWorker:1:QuorumCnxManager$RecvWorker@1179] - Interrupting SendWorker
2020-06-04 14:46:54,894 [myid:2] - WARN  [SendWorker:1:QuorumCnxManager$SendWorker@1097] - Exception when using channel: for id 1 my id = 2 error = java.net.SocketException: Broken pipe (Write failed)
2020-06-04 14:46:54,895 [myid:2] - WARN  [SendWorker:1:QuorumCnxManager$SendWorker@1102] - Send worker leaving thread  id 1 my id = 2
2020-06-04 14:46:56,259 [myid:2] - INFO  [NIOWorkerThread-1:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:60052
2020-06-04 14:46:56,730 [myid:2] - WARN  [NIOWorkerThread-2:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2020-06-04 14:46:57,592 [myid:2] - WARN  [NIOWorkerThread-1:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2020-06-04 14:47:01,813 [myid:2] - INFO  [NIOWorkerThread-2:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:60214

From the first node i get the following:

> 2020-06-04 14:56:13,923 [myid:1] - INFO  [NIOWorkerThread-2:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:55532
2020-06-04 14:56:15,396 [myid:1] - WARN  [ProcessThread(sid:1 cport:-1)::PrepRequestProcessor@432] - skipACL is set, reconfig operation will skip ACL checks!
2020-06-04 14:56:15,396 [myid:1] - INFO  [ProcessThread(sid:1 cport:-1)::PrepRequestProcessor@474] - Incremental reconfig
2020-06-04 14:56:15,398 [myid:1] - WARN  [ProcessThread(sid:1 cport:-1)::PrepRequestProcessor@547] - Reconfig failed - there must be a connected and synced quorum in new configuration
2020-06-04 14:56:15,398 [myid:1] - INFO  [ProcessThread(sid:1 cport:-1)::PrepRequestProcessor@878] - Got user-level KeeperException when processing sessionid:0x10177571eb600df type:reconfig cxid:0x1 zxid:0x100000200 txntype:-1 reqpath:n/a Error Path:null Error:KeeperErrorCode = NewConfigNoQuorum
2020-06-04 14:56:15,742 [myid:1] - WARN  [NIOWorkerThread-1:NIOServerCnxn@366] - Unable to read additional data from client sessionid 0x10177571eb600df, likely client has closed socket
2020-06-04 14:56:17,013 [myid:1] - INFO  [NIOWorkerThread-2:NIOServerCnxn@518] - Processing ruok command from /127.0.0.1:55582
2020-06-04 14:56:17,820 [myid:1] - WARN  [ProcessThread(sid:1 cport:-1)::PrepRequestProcessor@432] - skipACL is set, reconfig operation will skip ACL checks!
2020-06-04 14:56:17,821 [myid:1] - INFO  [ProcessThread(sid:1 cport:-1)::PrepRequestProcessor@474] - Incremental reconfig
2020-06-04 14:56:18,195 [myid:1] - WARN  [NIOWorkerThread-1:NIOServerCnxn@366] - Unable to read additional data from client sessionid 0x10177571eb600e0, likely client has closed socket

Thanks in advance.

**Comment by Prabhaker24** [comment]
@2phost did you try with Istio enabled without MTLS ?

**Comment by Prabhaker24** [comment]
I have tried it without MTLS and all the pods came up for me, I am pasting the output as well for your reference:- 
```
prabhaker@prabhaker-VirtualBox:~/Documents/from2020/code$ kubectl get pods
NAME                                               READY   STATUS      RESTARTS   AGE
grafana-698d64686d-mw55q                           1/1     Running     0          85m
istio-citadel-86f875bb9f-67r6t                     1/1     Running     0          85m
istio-galley-5695749f55-llz7z                      1/1     Running     0          85m
istio-grafana-post-install-1.4.2-44km7             2/2     Running     0          85m
istio-ingressgateway-69544cf6cd-drhbb              1/1     Running     0          85m
istio-init-crd-10-1.4.2-47dk7                      0/1     Completed   0          86m
istio-init-crd-11-1.4.2-vl9cm                      0/1     Completed   0          86m
istio-init-crd-14-1.4.2-k7vwp                      0/1     Completed   0          86m
istio-pilot-65d78db94b-26g5v                       2/2     Running     0          85m
istio-policy-5b7cddc6f5-hzpp6                      2/2     Running     0          85m
istio-sidecar-injector-6447b4c8c5-95x8k            1/1     Running     0          85m
istio-telemetry-6bb66ff56d-bj8vz                   2/2     Running     0          85m
pravega-zk-0                                       2/2     Running     0          2m59s
pravega-zk-1                                       2/2     Running     0          2m26s
pravega-zk-2                                       2/2     Running     0          102s
prometheus-5bc799fd4c-pgbgd                        1/1     Running     0          85m
zookeeper-operator-5b95866bbb-sqxbn                2/2     Running     2          79m

```

**Comment by 2phost** [comment]
I just created a PeerAuthentication and a DestinationRule  to make sure that I disable MTLS, and it keeps showing these errors.

If I do a ```kubectl get pods -n zookeeper-system``` the status is running, but the logs says otherwise:                                                                                                                                                                   
```
NAME                                 READY   STATUS    RESTARTS   AGE
zk-with-istio-0                      2/2     Running   1          5m35s
zk-with-istio-1                      2/2     Running   1          5m2s
zk-with-istio-2                      2/2     Running   1          4m30s
zookeeper-operator-988fbb885-78wtw   2/2     Running   1          8m53s
```
Is there any way to switch the logging to DEBUG level?


I tried to check if it is something DNS related, but everything seems to be ok, I can resolve all the required services.

**Comment by Prabhaker24** [comment]
oh I see does this https://github.com/pravega/zookeeper-operator/pull/194 fixes this issue?

**Comment by 2phost** [comment]
No.
I was checking why all of my pods had 1 restart and found out that Envoy was starting after Zookeeper. After the fix I now have 0 restarts but this problem continues.

I deployed exactly the same configurations in a local environment and everything seems to work, but I  need this to work on my remote kubernetes cluster, as such I am trying to understand what it is happening here.

I've already debugged the Istio network (activating DEBUG logging in all envoys) and everything seems to be fine, but for some reason Zookeeper refuses to have a quorum.

**Comment by whitleykeith** [comment]
@2phost We've noticed this as well within our own remote cluster. I've been able to get mTLS working with Zookeeper on my local K8s cluster, but remote seems to have issues. 

A few of my observations:

- It seems like mTLS Auto works fine with ZK on my local, but not remote. The only difference between the two for us is K8 Versions (EKS 1.15 vs Docker-Desktop 1.16) and that our remote uses CNI over the init-container startup for the networking setup.

- I was able to get mTLS strict enabled for a bit, but I had to delete the ZK PVCs to do so. Even so Solr wasn't able to connect to ZK for me locally so I didn't test that out a whole lot.


Also there was some related monitoring issues around ZK that should be resolved by https://github.com/pravega/zookeeper-operator/pull/184 once it's merged

**Comment by 2phost** [comment]
@whitleykeith Thanks for your observations! I definitely will check differences between docker and kubernetes versions. BTW, I am using Istio 1.6 in both.

At the moment, the only difference I found between my two configurations is that, in my local environment I use weave as CNI and the remote environment uses Canal. However I do not think that that is the issue.

I am out this week, but next week I will continue with some research on this problem and, as soon as I have news, I will post here.

@whitleykeith may I ask you what CNI have your remote cluster (the one with problems)?

**Comment by whitleykeith** [comment]
We just use the default CNI for our version (docker.io/istio/install-cni:1.5.1), however we're also on EKS which uses AWS CNI as well.

Similar for us where I don't think it's CNI but it's the only difference between the two environments for us. I'll keep looking and let you know if I find anything as well.

**Comment by kriston13** [comment]
Hi,

I've just run into this problem as well.

This is the Zookeeper yaml I'm using

```yaml

# Source: solr-cloud/templates/zookeeper.yaml
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: "test-zk"
spec:
  replicas: 3
  config:
    initLimit: 10
    tickTime: 2000
    syncLimit: 5
    quorumListenOnAllIPs: true

```


However, when I apply this, this is the `ConfigMap` that I get:

```
Name:         test-zk-configmap
Namespace:    jt-solr
Labels:       <none>
Annotations:  <none>

Data
====
env.sh:
----
#!/usr/bin/env bash

DOMAIN=test-zk-headless.jt-solr.svc.cluster.local
QUORUM_PORT=2888
LEADER_PORT=3888
CLIENT_HOST=test-zk-client
CLIENT_PORT=2181
CLUSTER_NAME=test-zk
CLUSTER_SIZE=3

log4j-quiet.properties:
----
log4j.rootLogger=ERROR, CONSOLE
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Threshold=ERROR
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n

log4j.properties:
----
zookeeper.root.logger=CONSOLE
zookeeper.console.threshold=INFO
log4j.rootLogger=${zookeeper.root.logger}
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Threshold=${zookeeper.console.threshold}
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n

zoo.cfg:
----
4lw.commands.whitelist=cons, envi, conf, crst, srvr, stat, mntr, ruok
dataDir=/data
standaloneEnabled=false
reconfigEnabled=true
skipACL=yes
initLimit=10
syncLimit=5
tickTime=2000
dynamicConfigFile=/data/zoo.cfg.dynamic

Events:  <none>

```

Notably, the quorum flag isn't in the `zoo.cfg` block.


I have tried changing `initLimit`, `syncLimit`, and `tickTime` in the yaml, and those had the expected changes to the ConfigMap. It's just the `quorumListenOnAllIPs` config value that doesn't seem to be working.

Taking a look at my `zookeeper-operator`, I can see that the tag is `0.2.7`, which is also the latest that I can find on docker hub.

```
Containers:
  zk-operator-zookeeper-operator:
    Container ID:  docker://7d96cb1ea77010bc0c98f800990992004a967d150f9dd822753374195f70a789
    Image:         pravega/zookeeper-operator:0.2.7
    Image ID:      docker-pullable://pravega/zookeeper-operator@sha256:fcf54074bbf95fbe4baa3ca00c31d65a4b0de8ebb68d2787
```

The way that the ConfigMap looks and the way that the `makeZkConfigString` function in the `generators.go` file looks, I'm actually guessing that the code to add the parameter in the published docker image is completely missing.

Unfortunately, I've got no clue how to continue debugging this.

**Comment by 2phost** [comment]
Hey @kriston13 ,

I believe that the Istio supported version is not in the docker hub yet.
The version that I am running is from Git and I have the flag correctly set: quorumListenOnAllIPs=true

**Comment by kriston13** [comment]
Oh. And you can see that in the ConfigMap?
Well, damn. How do I get that version of the zookeeper-operator...? lol

**Comment by anishakj** [comment]
we will be releasing the image with the changes in this week.

**Comment by anishakj** [comment]
> we will be releasing the image with the changes in this week.
We have released `0.2.8-rc0` in docker hub which has istio changes

**Comment by 2phost** [comment]
I just changed the provider (due to some support issues) and hoped this could be resolved. Unfortunately, I got the same error, therefore I can discard issues about the network configuration. I will double check Istio configurations.

**Comment by anishakj** [comment]
Could you please share the zookeeper logs?

**Comment by 2phost** [comment]
sure.
Today I changed to the new release (due to the upgrade of the zookeeper version) and got a new error:
```Have smaller server identifier, so dropping the connection```

I know that this could be related with the Zookeeper directly, and sometimes it can be resolved restarting all nodes, but it did not work.

I am running three instances of zookeeper. Please find the logs attached.

[zookeeper0.txt](https://github.com/pravega/zookeeper-operator/files/4972374/zookeeper0.txt)
[zookeeper1.txt](https://github.com/pravega/zookeeper-operator/files/4972375/zookeeper1.txt)
[zookeeper2.txt](https://github.com/pravega/zookeeper-operator/files/4972376/zookeeper2.txt)

**Comment by 2phost** [comment]
For now, (as workaround) I manage to get it working.

I put the following:
```
annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "2888,3888"
        traffic.sidecar.istio.io/excludeOutboundPorts: 2888,3888
```
