### ISSUE TITLE
Error trying to run the operator locally

### ISSUE THREAD

**Issue by adrianmo** [pravega/zookeeper-operator#24]
I'm trying to run the operator locally as instructed in the [operator-sdk user guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#2-run-outside-the-cluster) using the `operator-sdk up local` command. However, the operators panics and outputs the following log:

```
$ operator-sdk up local
INFO[0000] Go Version: go1.11
INFO[0000] Go OS/Arch: linux/amd64
INFO[0000] operator-sdk Version: 0.0.5+git
INFO[0000] Watching zookeeper.pravega.io/v1beta1, ZookeeperCluster, default, 5
panic: No Auth Provider found for name "gcp"

goroutine 1 [running]:
github.com/pravega/zookeeper-operator/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1.NewForConfigOrDie(0xc000394000, 0xc0003e62d0)     
        /home/adrian/.gvm/pkgsets/go1.11/global/src/github.com/pravega/zookeeper-operator/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1/admissionregistration_client.go:58 +0x65
github.com/pravega/zookeeper-operator/vendor/k8s.io/client-go/kubernetes.NewForConfigOrDie(0xc000394000, 0x0)                                                   
        /home/adrian/.gvm/pkgsets/go1.11/global/src/github.com/pravega/zookeeper-operator/vendor/k8s.io/client-go/kubernetes/clientset.go:529 +0x49             
github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient.mustNewKubeClientAndConfig(0x59, 0xc0001f5c30, 0xe840f0)  
        /home/adrian/.gvm/pkgsets/go1.11/global/src/github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient/client.go:138 +0x68
github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient.newSingletonFactory()                                     
        /home/adrian/.gvm/pkgsets/go1.11/global/src/github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient/client.go:52 +0x34
sync.(*Once).Do(0x1ba0390, 0x1146e50)
        /home/adrian/.gvm/gos/go1.11/src/sync/once.go:44 +0xb3
github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient.GetResourceClient(0x10e256f, 0x1c, 0x10d7753, 0x10, 0xc00003e470, 0x7, 0xc000430580, 0xc0001f5e20, 0xe8304e, 0xc0004e6410, ...)
        /home/adrian/.gvm/pkgsets/go1.11/global/src/github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient/client.go:70 +0x3d
github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk.Watch(0x10e256f, 0x1c, 0x10d7753, 0x10, 0xc00003e470, 0x7, 0x12a05f200, 0x0, 0x0, 0x0)
        /home/adrian/.gvm/pkgsets/go1.11/global/src/github.com/pravega/zookeeper-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/api.go:45 +0x84
main.main()
        /home/adrian/.gvm/pkgsets/go1.11/global/src/github.com/pravega/zookeeper-operator/cmd/zookeeper-operator/main.go:31 +0x215                              
exit status 2
Error: failed to run operator locally: exit status 1
```

We also experienced this error with the Pravega operator (https://github.com/pravega/pravega-operator/issues/39) and fixed it by importing the `gcp` package. Will apply the same fix and submit a PR.

**Comment by anishakj** [comment]
This issue is fixed not seen with latest code
