### ISSUE TITLE
Zookeeper cluster got corrupted

### ISSUE THREAD

**Issue by vishalgarg837** [pravega/zookeeper-operator#477]
### Description

We are using zookeeper-operator 0.2.14 for the last couple of weeks. It was running fine till now but suddenly we started seeing the following error in the zookeeper:
```
FATAL [main:QuorumPeer@400] - Unable to load database on disk 
Caused by: java.io.IOException: Unreasonable length = 6559049
at org.apache.jute.BinaryInputArchive.checkLength(BinaryInputArchive.java:166)
at org.apache.jute.BinaryInputArchive.readBuffer(BinaryInputArchive.java:127)
at org.apache.zookeeper.server.persistence.Util.readTxnBytes(Util.java:159)
at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.next(FileTxnLog.java:768)
at org.apache.zookeeper.server.persistence.FileTxnSnapLog.fastForwardFromEdits(FileTxnSnapLog.java:352)
at org.apache.zookeeper.server.persistence.FileTxnSnapLog.lambda$restore$0(FileTxnSnapLog.java:258)
at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:303)
at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:285)
at org.apache.zookeeper.server.quorum.QuorumPeer.loadDataBase(QuorumPeer.java:1094)
```
### Importance

For now, we resolved it by removing the persistent volume and restarting the cluster but it might happen again so wanted to understand the root cause.

**Comment by fujin** [comment]
I've hit the same in two of my zookeeper-operator managed zookeeper clusters, we're investigating increasing jute.maxbuffer to e.g. 10MiB across all clients/servers.

**Comment by vishalgarg837** [comment]
I am again seeing this issue today. @fujin Can you please tell me, are you setting this `jute.maxbuffer` config through zookeeper-operator if yes then where did you set it?

**Comment by fujin** [comment]
@vishalgarg837 yeah that fixed it for us.
``` yaml
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  pod:
    env:
      - name: JVMFLAGS
        value: "-Djute.maxbuffer=0x9fffff"
```
        
make sure you set it on all of your clients too.

**Comment by vishalgarg837** [comment]
Thanks, @fujin. It works for us as well.
