### ISSUE TITLE
Zookeeper pods fail to come back up when > quorum number of pods are deleted.

### ISSUE THREAD

**Issue by pbelgundi** [pravega/zookeeper-operator#92]
Steps to Reproduce:
1. Create a 3 node zookeeper cluster.
2. Once cluster is up and running delete 2 or more pods from the cluster using `kubectl delete`.
3. The new restarted pods are not able to join back the zk cluster becuase of lack of quorum and logs show the following error message:
"
Error performing zookeeper reconfiguration:
org.apache.zookeeper.KeeperException$NewConfigNoQuorum: KeeperErrorCode = NewConfigNoQuorum
at org.apache.zookeeper.KeeperException.create(KeeperException.java:110)
at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
at org.apache.zookeeper.ZooKeeper.internalReconfig(ZooKeeper.java:3081)
at org.apache.zookeeper.admin.ZooKeeperAdmin.reconfigure(ZooKeeperAdmin.java:174)
at io.pravega.zookeeper.MainKt.reconfigure(Main.kt:99)
at io.pravega.zookeeper.MainKt.runAdd(Main.kt:122)
at io.pravega.zookeeper.MainKt.main(Main.kt:29)
"

**Comment by pbelgundi** [comment]
To fix this issue properly it is important to change the way we handle pod restart in zookeeper and zookeeper-operator.

Currently, everytime a zk server goes down, the `tearDown` script removes it from the zk ensemble and the startup script tries to add it back again.

This works fine as long as we have > Quorum number of servers available. However, when we have < quorum servers in Ready state, this causes the newly restarting servers to hang during `reconfiguration` operation as `Quorum` is not available.

A better way to deal with server deletion would be to try and identify sever unavailability as a `temporary` or `permanent`. In case of `temporary` unavailability( node unexpectedly going down because of hardware failure or other issues) there is no need to remove the server from zk ensemble and add it back on restart. Only in case of permanent removal of a server from the ensemble (a scale down operation) the zookeeper operator should invoke "reconfiguration" on the zk servers to remove the server from quorum.

This requires making 2 changes:

Change existing zookeeper startup, shutdown and readiness scripts to deal with server restarts without invoking "reconfig".
Change `zookeeper-operator` code to invoke reconfig() for the servers being removed when zookeeper cluster is being scaled down.
