### ISSUE TITLE
Zookeeper instances fail to start on second scale up

### ISSUE THREAD

**Issue by pbelgundi** [pravega/zookeeper-operator#94]
## Problem description
Had a pravega installation with 7 zookeeper . 
scaled down zk from 7 to 5 and then 3 .
IO was running fine .No pod restarts were observed.
Later on scaled up from 3 instances of zookeeper to 5 instances .
observed zookeeper pods restarts 
Error observed:

2019-10-17 10:05:58,998 [myid:6] - ERROR [main:QuorumPeerMain@101] - Unexpected exception, exiting abnormally
java.lang.RuntimeException: My id 6 not in the peer list
        at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:903)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)

**Comment by pbelgundi** [comment]
Could consistently reproduce this issue on zk server "scale up" for the second time.

This issue occurs when  zk server is "scaled up", "scaled down" and then "scaled up" again and a newly starting pod points to an existing PVC that has stale configuration on it.

It is not reproducible by restarting existing servers or on first scale-up/scale down.

**Comment by pbelgundi** [comment]
when cluster is "scaled down" after being "scaled-up" the new PVCs created during scale-up are not deleted/removed on "scale down". Hence on the next scale-up these are re-attached to the newly added pods and have inconsistent state information.

Zookeeper-operator does have a finalizer for removing PVCs on cluster delete, but it does not seem to work as expected in this case.
